{% set name = "partialjson" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0af7035ed8d0194691d9e015302a462f61a732271e927d81a5a0971ee2fe38fd

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - partialjson
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iw4p/partialjson
  summary: Parse incomplete or partial json
  description: Parse incomplete or partial json
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/iw4p/partialjson

extra:
  recipe-maintainers:
    - raybellwaves

